# Generated by Django 3.1 on 2021-04-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210420_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='preview_img_url',
            new_name='preview_image_url',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='short_text',
            new_name='preview_text',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
