# Generated by Django 3.1 on 2021-04-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210420_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_text',
            field=models.TextField(max_length=500),
        ),
    ]
