# Generated by Django 3.1 on 2021-04-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210421_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_message',
            field=models.CharField(max_length=100),
        ),
    ]
